name: Build and push

on:
  push:
    branches: [ master ]

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    env:
      PackageVersion: 0.1.0.${{ github.run_number }}
      PackageName: TypeVisitor.0.1.0.${{ github.run_number }}.nupkg
      PackagePath: ./bin/release/packs
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.100
        source-url: https://nuget.pkg.github.com/CyberMonster/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      run: dotnet build --configuration Release -p:Version=${{ env.PackageVersion }}
    - name: build package
      run: dotnet pack --configuration Release --output ${{ env.PackagePath }} -p:Version=${{ env.PackageVersion }}
    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: art-${{ env.PackageVersion }}
        path: ${{ env.PackagePath }}/${{ env.PackageName }}
    - name: push github
      run: dotnet nuget push "${{ env.PackagePath }}/${{ env.PackageName }}" --skip-duplicate
    - name: push nuget
      run: dotnet nuget push "${{ env.PackagePath }}/${{ env.PackageName }}" --source "https://api.nuget.org/v3/index.json" --api-key ${{secrets.nuget_apiKey}} --skip-duplicate